services:

  role-reactor-bot:
    build: .
    container_name: role-reactor-bot
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs:rw
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3030:3030"
    # Port is exposed locally to the host for Nginx to proxy to
    networks:
      - role-reactor-prod
    # Healthcheck is defined in the Dockerfile


networks:
  role-reactor-prod:
    driver: bridge
