services:
  role-reactor-bot:
    build: .
    container_name: role-reactor-bot
    restart: unless-stopped
    # Ensure proper permissions for mounted volumes
    user: "1001:1001"
    env_file:
      - .env.production
    volumes:
      # Mount data directory for persistent storage
      - ./data:/usr/src/app/data
      # Mount logs directory with proper permissions
      - ./logs:/usr/src/app/logs:rw
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    # Use production CMD from Dockerfile
    # No need to override command for production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3030/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 